---
description: Предупреждение компилятора (уровень 2) CS0162
title: Предупреждение компилятора (уровень 2) CS0162
ms.date: 07/20/2015
f1_keywords:
- CS0162
helpviewer_keywords:
- CS0162
ms.assetid: 369b5b02-a9cc-404b-b758-4184285af2de
ms.openlocfilehash: 584faebca993de75c6e02f0b3d885fa547be8cea
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100424297"
---
# <a name="compiler-warning-level-2-cs0162"></a>Предупреждение компилятора (уровень 2) CS0162

Обнаружен недостижимый код
  
Компилятор обнаружил код, который никогда не будет выполняться.

## <a name="example"></a>Пример

Следующий пример приводит к возникновению ошибки CS0162:

```csharp
// CS0162.cs
// compile with: /W:2
public class Program
{
    public static void Main()
    {
        goto lab1;
        {
            // The following statements cannot be reached:
            int i = 9;   // CS0162
            i++;
        }
    lab1:
        {
        }
    }
}
```

Другой распространенный пример, в котором возникает эта ошибка:

```csharp
public static class Class1
{
    public static string Method1()
    {
        string x = "a";
        switch (x)
        {
            case "a":
                return "a";
                break;          // CS0162
        }
        return "";
    }
}
```

Инструкция недоступна, `break` так как она выполняется после `return` инструкции.
`return`Оператор завершает включающую `case` ветвь.
