---
description: 'Дополнительные сведения: "Catch" не может перехватывать тип " <typename> ", так как он не является "System. Exception" или классом, наследуемым от "System. Exception"'
title: "\"Catch\" не может перехватить тип \"<typename>\", так как не является \"System.Exception\" или классом, наследующим от \"System.Exception\""
ms.date: 07/20/2015
f1_keywords:
- vbc30392
- bc30392
helpviewer_keywords:
- BC30392
ms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803
ms.openlocfilehash: cc1c96e284a29f357523729bfcca1af02c693dfd
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100428406"
---
# <a name="catch-cannot-catch-type-typename-because-it-is-not-systemexception-or-a-class-that-inherits-from-systemexception"></a>"Catch" не может перехватить тип "\<typename>", так как не является "System.Exception" или классом, наследующим от "System.Exception"

`Catch` может перехватывать только исключения, и была предпринята попытка перехвата объекта, не являющегося производным от исключения.  
  
 **Идентификатор ошибки:** BC30392  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
1. Удалите оператор `Catch` или измените целевой объект оператора `Catch` на действительное исключение.  
  
## <a name="see-also"></a>См. также раздел

- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
