---
description: 'Дополнительные сведения: операнд "Throw" должен быть производным от "System. Exception"'
title: Операнд оператора Throw должен быть производным от System.Exception
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 9b21a9f580a23d8c21e3f25ec9cd0773bcb92345
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100477207"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>Операнд оператора Throw должен быть производным от System.Exception

Аргумент для `Throw` должен быть либо экземпляром `System.Exception` , либо экземпляром класса, производного от `System.Exception`.  
  
 **Идентификатор ошибки:** BC30665  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
- Используйте аргумент, производный от `System.Exception`, как показано в приведенном ниже примере.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>См. также раздел

- [Оператор Throw](../language-reference/statements/throw-statement.md)
- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Обработка и создание исключений в .NET](../../standard/exceptions/index.md)
