---
description: 'Дополнительные сведения о: блок "Catch" никогда не достигается, так как " <name1> " наследуется от " <name2> "'
title: Блок "Catch" никогда не достигается, поскольку " <name1> " наследуется от " <name2> "
ms.date: 07/20/2015
f1_keywords:
- BC42029
- vbc42029
helpviewer_keywords:
- BC42029
ms.assetid: 4bc84a84-ec7e-49db-8794-4fb71d36d5c0
ms.openlocfilehash: 9fbbad2d11f261f68ad1e4f63cb691805d59995e
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 02/14/2021
ms.locfileid: "100422761"
---
# <a name="catch-block-never-reached-because-name1-inherits-from-name2"></a>Блок "Catch" никогда не достигается, поскольку " \<name1> " наследуется от " \<name2> "

Блок `Catch` в коде никогда не будет достигнут.  
  
 По умолчанию данное сообщение является предупреждением. Дополнительные сведения о скрытии предупреждений или обработке предупреждений как ошибок см. в разделе [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).  
  
 **Идентификатор ошибки:** BC42029  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
- Удалите лишний блок `Catch` .  
  
## <a name="see-also"></a>См. также раздел

- [Использование блока try/catch для перехвата исключений](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Оператор Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
